name: lint-code

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight

  push:
    branches:
      - develop
      - main

    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      # https://semver.org/ proper release tags, more or less
      - 'v[0-9]+.[0-9]+.[0-9]+'
      # prerelease tags, more or less
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

  pull_request:
    branches:
      - develop
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        if: ${{ !env.ACT }}
        uses: actions/checkout@v2
      - uses: hadenlabs/action-pre-commit@0.1.8
        with:
          args: run --all-files
